---
title: Upstream Landing Page
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: drafts
  values:
    layout: post
markdown: kramdown
highlighter: rouge
paginate: 20
baseurl: "/upstream/"
name: "Upstream"
domain_name: http://upstreamapp.io
links:
  docs: https://hertzlersystems.atlassian.net/wiki/display/UD/Getting+Started
  login: https://api.upstreamapp.io/login?redirect=https://www.upstreamapp.io/
  signup: https://api.upstreamapp.io/signup
  privacy: https://hertzlersystems.atlassian.net/wiki/display/UD/Upstream+Privacy+Policy
  contact: mailto:upstreamapp.io@gmail.com
prose:
  media: assets/images
url: http://upstreamapp.io
# author: Micah Miller-Eshleman
# authorTwitter: YourTwitterUsername
permalink: "/:year/:title/"
